name: Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Checkout code
      uses: actions/checkout@v2
      with:
          ref: ${{ github.ref }}

    - name: Build
      run: go build